/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_Main */

#ifndef _Included_com_example_Main
#define _Included_com_example_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_Main
 * Method:    jniWeakUser
 * Signature: ()Lcom/example/User;
 */
JNIEXPORT jobject JNICALL Java_com_example_Main_jniWeakUser
  (JNIEnv *, jobject);

/*
 * Class:     com_example_Main
 * Method:    helloFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_Main_helloFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
